/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartPluginPanel.java
 *
 * Created on Aug 12, 2010, 1:35:03 AM
 */

package se.uu.bmc.it.batchelor.explorer.plugin;

import javax.swing.JPanel;
import se.uu.bmc.it.batchelor.explorer.WebServiceClient;

/**
 *
 * @author Anders Lövgren (QNET/BMC CompDept)
 */
public class StartPluginPanel extends JPanel implements PluginPanelInterface {

    /** Creates new form StartPluginPanel */
    public StartPluginPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabelStart = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaInformation = new javax.swing.JTextArea();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(se.uu.bmc.it.batchelor.explorer.BatchelorExplorerApp.class).getContext().getResourceMap(StartPluginPanel.class);
        jLabelStart.setBackground(resourceMap.getColor("jLabelStart.background")); // NOI18N
        jLabelStart.setFont(resourceMap.getFont("jLabelStart.font")); // NOI18N
        jLabelStart.setIcon(resourceMap.getIcon("jLabelStart.icon")); // NOI18N
        jLabelStart.setText(resourceMap.getString("jLabelStart.text")); // NOI18N
        jLabelStart.setBorder(null);
        jLabelStart.setName("jLabelStart"); // NOI18N
        jLabelStart.setOpaque(true);

        jScrollPane.setName("jScrollPane"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextAreaInformation, org.jdesktop.beansbinding.ELProperty.create("${border}"), jScrollPane, org.jdesktop.beansbinding.BeanProperty.create("border"));
        bindingGroup.addBinding(binding);

        jTextAreaInformation.setColumns(20);
        jTextAreaInformation.setEditable(false);
        jTextAreaInformation.setLineWrap(true);
        jTextAreaInformation.setRows(5);
        jTextAreaInformation.setText(resourceMap.getString("jTextAreaInformation.text")); // NOI18N
        jTextAreaInformation.setWrapStyleWord(true);
        jTextAreaInformation.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextAreaInformation.setName("jTextAreaInformation"); // NOI18N
        jTextAreaInformation.setOpaque(false);
        jScrollPane.setViewportView(jTextAreaInformation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelStart, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextAreaInformation;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setActive(boolean active) {
	setVisible(active);
    }

    @Override
    public void setService(WebServiceClient service) {
	// ignore
    }

}
