//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.21 at 02:17:41 AM CEST 
//


package se.uu.bmc.it.batchelor.rest.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for job complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="job">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jobid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="finished" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="stdout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="started" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="queued" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "job", propOrder = {
    "jobid",
    "finished",
    "stdout",
    "started",
    "queued",
    "state",
    "result"
})
public class Job {

    @XmlElement(required = true)
    protected String jobid;
    protected int finished;
    protected int stdout;
    protected int started;
    protected int queued;
    @XmlElement(required = true)
    protected String state;
    protected int result;
    @XmlAttribute
    protected String timezone;

    /**
     * Gets the value of the jobid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * Sets the value of the jobid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobid(String value) {
        this.jobid = value;
    }

    /**
     * Gets the value of the finished property.
     * 
     */
    public int getFinished() {
        return finished;
    }

    /**
     * Sets the value of the finished property.
     * 
     */
    public void setFinished(int value) {
        this.finished = value;
    }

    /**
     * Gets the value of the stdout property.
     * 
     */
    public int getStdout() {
        return stdout;
    }

    /**
     * Sets the value of the stdout property.
     * 
     */
    public void setStdout(int value) {
        this.stdout = value;
    }

    /**
     * Gets the value of the started property.
     * 
     */
    public int getStarted() {
        return started;
    }

    /**
     * Sets the value of the started property.
     * 
     */
    public void setStarted(int value) {
        this.started = value;
    }

    /**
     * Gets the value of the queued property.
     * 
     */
    public int getQueued() {
        return queued;
    }

    /**
     * Sets the value of the queued property.
     * 
     */
    public void setQueued(int value) {
        this.queued = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the result property.
     * 
     */
    public int getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     */
    public void setResult(int value) {
        this.result = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

}
