//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.04 at 04:46:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://it.bmc.uu.se/batchelor/rest/200901")
package se.uu.bmc.it.batchelor.rest.schema;
