//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.04 at 04:46:13 PM CEST 
//
package se.uu.bmc.it.batchelor.rest.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for job complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="job">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jobid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="queued" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="started" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="finished" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stdout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stderr" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stamp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "job", propOrder = {
    "jobid",
    "result",
    "queued",
    "started",
    "finished",
    "stdout",
    "stderr",
    "state",
    "name",
    "date",
    "time",
    "stamp"
})
public class Job {

    @XmlElement(required = true)
    protected String jobid;
    protected Integer result;
    protected Integer queued;
    protected Integer started;
    protected Integer finished;
    protected Integer stdout;
    protected Integer stderr;
    protected String state;
    protected String name;
    protected String date;
    protected String time;
    protected Integer stamp;
    @XmlAttribute
    protected String timezone;

    /**
     * Gets the value of the jobid property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * Sets the value of the jobid property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setJobid(String value) {
        this.jobid = value;
    }

    /**
     * Gets the value of the result property.
     *
     * @return
     */
    public Integer getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     *
     * @param value
     */
    public void setResult(Integer value) {
        this.result = value;
    }

    /**
     * Gets the value of the queued property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getQueued() {
        return queued;
    }

    /**
     * Sets the value of the queued property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setQueued(Integer value) {
        this.queued = value;
    }

    /**
     * Gets the value of the started property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getStarted() {
        return started;
    }

    /**
     * Sets the value of the started property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setStarted(Integer value) {
        this.started = value;
    }

    /**
     * Gets the value of the finished property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getFinished() {
        return finished;
    }

    /**
     * Sets the value of the finished property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setFinished(Integer value) {
        this.finished = value;
    }

    /**
     * Gets the value of the stdout property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getStdout() {
        return stdout;
    }

    /**
     * Sets the value of the stdout property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setStdout(Integer value) {
        this.stdout = value;
    }

    /**
     * Gets the value of the stderr property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getStderr() {
        return stderr;
    }

    /**
     * Sets the value of the stderr property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setStderr(Integer value) {
        this.stderr = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the stamp property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getStamp() {
        return stamp;
    }

    /**
     * Sets the value of the stamp property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setStamp(Integer value) {
        this.stamp = value;
    }

    /**
     * Gets the value of the timezone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

}
